fileRoutes:
    MyBusinessRoute: /ficheros_oficinas/MyBusiness_20102020.csv
    OficinasTotalesRoute: OficinasTotales TEXT
    OficinasEnAltaRoute: OficinasEnAlta TEXT
    OficinasEnBaja: OficinasEnBaja TEXT
    OficinasModificadas: OficinasModificadas TEXT
constants:
    NumeroMinimoDeBajasParaEnviarCorreo: 11