fileRoutes:
    MyBusinessRoute: "MyBusinessRoute TEXT"
    OficinasTotalesRoute: "OficinasTotales TEXT"
    OficinasEnAltaRoute: "OficinasEnAlta TEXT"
    OficinasEnBaja: "OficinasEnBaja TEXT"
    OficinasModificadas: "OficinasModificadas TEXT"
...